### ISSUE TITLE
Data Tables input file header typo?

### ISSUE THREAD

**Issue by jcramer-bc** [jobehrendt/OpenWasteWater#3]
In the files `Resources/ASM1/Inf_rain.txt` and `Resources/ASM1/Inf_strm.txt` the first line is `#14`.   Shouldn't this be `#1` per Modelica Tables spec?  It seems OM still loads the file fine with `#14`, but I just wanted to ask anyways in case I might learn some reason why `#14` was used.

**Comment by jobehrendt** [comment]
you are right only #1 is required. what follows does not matter.

**Comment by jcramer-bc** [comment]
Fixed in e86316291c545721f7f02ddb0e8163695a545297and b69f06cfdcbfc7a0f70fd53426a3b1b638fe465b.

**Comment by jobehrendt** [comment]
thanks
